pkg/osvscanner/osvscanner.go, pkg/osvscanner/vulnerability_result.go, pkg/osvscanner/vulnerability_result_internal_test.go
- Skips vulnerability detection.
- Return only the scanned packages from lockfile(s).
=> Internal option to scan and return the grouped sources (packages)

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/goreleaser.yml, .github/workflows/osv-scanner-reusable.yml, .github/workflows/prerelease-check.yml, .goreleaser.yml
What does this PR do?
---------------------
- Adding the OSV way of packaging the command line
- Adding a PR template
- Customizing config files to:
1. Refer to the Datadog github org instead of google one
2. Remove the generation of Docker images
- [JIRA link](https://datadoghq.atlassian.net/browse/APPSEC-18363)
Additional Notes
----------------
This PR only add workflows as the original repo handles it. In future PRs I'll create a README explaining how to use and release a new version, and also creating the LICENSE-3rdparty.csv mandatory file
=> Packaging OSV-Scanner

tasks/__init__.py, tasks/go.py, tasks/licenses.py, tasks/utils.py
- Importing python invoke tasks to automatically generate LICENSE-3rdparty.csv from go dependencies
This PR only import an existing tool from [datadog-agent](https://www.github.com/DataDog/datadog-agent) production branch. It has been separated from the other commits to ease the review.
=> :hammer: Import license generation and license linting tasks from datadog-agent repository

.copyright-overrides.yml, .prettierignore, .wwhrd.yml, LICENSE-3rdparty.csv, README.md, go.mod
- Updating configuration file to override copyright on libraries failing to automatically detecting them
- Generating the LICENSE-3rdparty.csv file
- Updating the README to add a section about LICENSE-3rd party generation
It is advised to review it commit by commit for a more comprehensive PR.
Please note everything in the commit [🔨 Adding license generation and license linting tasks from datadog-agent repository](https://github.com/DataDog/osv-scanner/commit/1ae01d916c7c828eaa0ff8d168a232762b2cc4b3) has been imported from  [datadog-agent](https://www.github.com/DataDog/datadog-agent) production branch.
=> :page_facing_up: Adding 3rd party license file and a way to generate it

.copyright-overrides.yml, .prettierignore, .wwhrd.yml, LICENSE-3rdparty.csv, README.md, go.mod
- Updating configuration file to override copyright on libraries failing to automatically detecting them
- Generating the LICENSE-3rdparty.csv file
- Updating the README to add a section about LICENSE-3rd party generation
It is advised to review it commit by commit for a more comprehensive PR.
Please note everything in the commit [🔨 Adding license generation and license linting tasks from datadog-agent repository](https://github.com/DataDog/osv-scanner/commit/1ae01d916c7c828eaa0ff8d168a232762b2cc4b3) has been imported from  [datadog-agent](https://www.github.com/DataDog/datadog-agent) production branch.
=> 📄 Adding 3rd party license file and a way to generate it

pkg/lockfile/fixtures/maven/children/with-parent.xml, pkg/lockfile/fixtures/maven/parent.xml, pkg/lockfile/fixtures/maven/with-project-version-property.xml, pkg/lockfile/parse-maven-lock.go, pkg/lockfile/parse-maven-lock_test.go
- We now deserialise the version tag to use it during dependencies version resolution
=> :adhesive_bandage: Deserialising project.version to use it with on dependencies version resolving

pkg/reporter/purl/golang_extractor.go, pkg/reporter/purl/golang_extractor_test.go
- golang packages expressed without a namespace (e.g. domains only package like [go.opencensus.io](https://pkg.go.dev/go.opencensus.io#section-readme)) are now reported with an empty namespace rather than being filtered.
**Why are we doing this :** In the [Package URL specifications](https://github.com/package-url/purl-spec/blob/master/PURL-SPECIFICATION.rst), namespace is defined as optional and type specific. As golang does not define it to be mandatory, we should report packages without namespace instead of filtering them
=> :bug: Fix DD SBOM reporter to extract name from packages without a namespace

pkg/lockfile/parse-pipenv-lock.go, pkg/lockfile/parse-pipenv-lock_test.go, pkg/lockfile/parse-requirements-txt.go, pkg/lockfile/parse-requirements-txt_test.go
- Include Start/End line for r`equirements.txt` lock files
- Fix `location_file` for -r packages (before, the `location_file` was always the main file for all the dependencies)
- Update unit tests for both line location and source file
- Include Start/End line for `Pipenv.lock` lock files
- Update unit tests for line location
- `Pipenv.lock` line location is enough right now, but ideally we should be reporting the line location of the file where the developer defines the dependencies, not of the lock file
- `Pipenv.lock` line location logic could be reused for other lock files: all of those that use `JSON` lock files
- For `requirements.txt`, no comments at all are included for the line location. Some of those would be interesting to be included in the future.
=> ✨ Detect line of code for Python/Pip

cmd/osv-scanner/main_test.go, internal/utility/lineposition/json.go, pkg/lockfile/parse-npm-lock-v1_test.go, pkg/lockfile/parse-npm-lock-v2_test.go, pkg/lockfile/parse-npm-lock.go, pkg/lockfile/parse-pipenv-lock.go, pkg/models/FilePosition.go
- Extract it from `parse-pipenv-lock.go` to `utility/lineposition/json`
- New struct `LinePosition` to hold both `Start` and `End` properties
- TODO: Refactor previous implementations to use this struct (`maven`, `requirements.txt`, etc.)
- TODO: Remove `FilePosition` struct (without the `column` property makes no sense any more)
- New interface `ILinePosition` to be able to generalize the usage of the function by defining the common setters for all structs implementing it
- Include Start/End line for `package-lock.json` lock files
- Update unit tests for line location
- Will be nice to have a `--debug` flag to be able to print some info and ease following the file scanning while finding the line position for the different libraries
- We will have to handle multiple positions for a …
=> ✨ Detect line of code for Javascript/npm

README.md, cmd/osv-scanner/main_test.go
- Updates the README run section to use a command exporting the SBOM instead of sending it to Datadog's backend
- Adds a release section with the process to follow
- Removing a flaky test
The removed test was flaky due to an external dependency download (the osv db) which has no option to fix on a specific version in OSV command line. As it is not a priority for Datadog to support this feature (only exporting an SBOM with location is), deleting it seems ok.
=> :memo: Updating README with release information and CycloneDX 1.4 command information

pkg/reporter/cyclonedx.go, pkg/reporter/cyclonedx_test.go
- Add the missing required component type to have a valid sbom
=> :bug: Add type in cyclone dx component

pkg/lockfile/fixtures/pip/whl-url-packages.txt, pkg/lockfile/parse-requirements-txt.go, pkg/lockfile/parse-requirements-txt_test.go
- Extracting version from the wheel package filename convention
- Wheel package filename convention is described [here](https://packaging.python.org/en/latest/specifications/binary-distribution-format/#file-name-convention)
=> ✨ Extract version from the wheel package filename convention

pkg/lockfile/fixtures/nuget/one-framework-one-package.v1.json, pkg/lockfile/fixtures/nuget/one-framework-two-packages.v1.json, pkg/lockfile/fixtures/nuget/two-frameworks-different-packages.v1.json, pkg/lockfile/fixtures/nuget/two-frameworks-duplicate-packages.v1.json, pkg/lockfile/fixtures/nuget/two-frameworks-mixed-packages.v1.json, pkg/lockfile/parse-nuget-lock.go
-  Ignoring project type 'dependencies' when scanning nuget's package.lock.json
=> :bug: Ignoring project 'dependencies' when scanning nuget's package.lock.json

pkg/models/location.go, pkg/reporter/sbom/cyclonedx_1_5.go
- [json.Encoder](https://pkg.go.dev/encoding/json#NewEncoder) add a new line at the end of the string
- See this [Stackoverflow question](https://stackoverflow.com/questions/36319918/why-does-json-encoder-add-an-extra-line)
- The location represented as json should not have a new line, `json.Marshal` is used instead
=> Remove trailing \n from location as JSON string

pkg/lockfile/fixtures/pnpm/scoped-packages-v6-lockfile.yaml, pkg/lockfile/parse-pnpm-lock.go
- Pnpm lockfiles version are not necessarily float64, handling them as string
=> :bug: Fixing bugs in PNPM lockfile parser

pkg/lockfile/fixtures/npm/link-dependency.v2.json, pkg/lockfile/parse-npm-lock-v1_test.go, pkg/lockfile/parse-npm-lock-v2_test.go, pkg/lockfile/parse-npm-lock.go
- Filtering dependencies flagged as "link" as it means they are defined elsewhere in the lockfile, they will be scanned at this moment
- Default version to 0.0.0 instead of skipping the entire package when it is not defined
- Default version to 0.0.0 instead of skipping the entire package when the dependency is defined as a local file
packages block specification : https://docs.npmjs.com/cli/v9/configuring-npm/package-lock-json#packages
specifically :
> link: A flag to indicate that this is a symbolic link. If this is present, no other fields are specified, since the link target will also be included in the lockfile.
=> :bug: Resolving bugs in npm lockfile parser

cmd/osv-scanner/main_test.go, pkg/osvscanner/osvscanner.go, pkg/osvscanner/vulnerability_result.go, pkg/reporter/cyclonedx.go, pkg/reporter/gh-annotations_reporter.go, pkg/reporter/json_reporter.go, pkg/reporter/reporter.go, pkg/reporter/sarif_reporter.go, pkg/reporter/table_reporter.go, pkg/reporter/void_reporter.go
- Add a warn mechanism in reporters with the same behaviour than Error but without considering the execution as a failure
- Demote some logs to a warn to avoid automated execution like CIs to fail because of a single package or lockfile failing to resolve
=> :loud_sound: Adding a warn mechanism to avoid blocking execution when a single lockfile/package is failing to entirely resolve

cmd/osv-scanner/main_test.go, pkg/lockfile/fixtures/go/with-path-major.mod, pkg/lockfile/fixtures/go/without-supported-versioning.mod, pkg/lockfile/parse-go-lock.go, pkg/lockfile/parse-go-lock_test.go, pkg/osvscanner/vulnerability_result.go
- Filtering out packages which are replaced by local directories as they will be scanned later in the OSV process
- Handle non-canonical versions in dependency declarations instead of failing the entire go.mod
go module major version documentation : https://go.dev/doc/modules/major-version
specifically the example on major version in path :
> In the new version’s go.mod file, append new major version number to the module path, as in the following example:
> Existing version: example.com/mymodule
> New version: example.com/mymodule/v2
=> :bug: Resolve bugs in go lockfile parser

pkg/lockfile/fixtures/maven/with-project-version-property.xml, pkg/lockfile/parse-maven-lock.go, pkg/lockfile/parse-maven-lock_test.go
- Fixing unexisting pom files instead of failing because parents can be located in an external registry
- Include all deserialized project direct properties
- Handling the now deprecated "pom" prefixed properties (replaced by "project" suffix but still in use)
- The POM file reference : https://maven.apache.org/pom.html
=> :bug:  Resolving bugs in maven pom file parser

pkg/lockfile/fixtures/pip/with-url-r-option.txt, pkg/lockfile/parse-requirements-txt.go, pkg/lockfile/parse-requirements-txt_test.go
- Skipping -r with URL when parsing requirements.txt instead of skipping the whole file with an error
=> :bug: Resolving bugs in python requirements.txt parser

pkg/grouper/package_grouper.go, pkg/grouper/package_grouper_test.go, pkg/models/location.go
This PR deduplicates locations to avoid reporting the same one multiple times.
Some package managers have a parenting system (yes I'm looking at you maven), which means that for a given lockfile we will reports its dependencies and the ones from its parent. Each lockfile parsing being independant, the same package is then reported multiple times, which will turn in the package grouper (which role is to turn packages grouped by source file in packages grouped by PURL) in one package with a duplicated location object.
=> :bug: deduplicate location object based on block locations

cmd/osv-scanner/main.go, cmd/osv-scanner/main_test.go, pkg/osvscanner/osvscanner.go
- adds the flag `--paths-relative-to-scan-dir` doing the same thing than `--consider-scan-path-as-root` but removes the leading path separator
=> ✨ Adding a relative path flag to report location relative to the scanned directory

cmd/osv-reporter/main.go, cmd/osv-scanner/main.go, cmd/osv-scanner/main_test.go
- Change the return code to 0 when no packages are detected, as empty repositories could want to start the scan right away without blocking everything
=> Change the non-zero output to zero when the detection is empty

cmd/osv-scanner/main.go, cmd/osv-scanner/main_test.go, pkg/lockfile/extract.go, pkg/lockfile/extract_test.go, pkg/osvscanner/osvscanner.go
This PR adds the possibility to explicitly choose the parsers in action when scanning the repository. For example, if you only want to reports from java maven and python requirements.txt you can set `--enable-parsers pom.xml --enable-parsers requirements.txt`. 
You can get the full list by running `osv-scanner --help`
=> ✨ Adding a flag to explicitly enable lockfiles

cmd/osv-scanner/main_test.go, pkg/grouper/package_grouper.go, pkg/lockfile/parse-go-lock.go, pkg/lockfile/parse-go-lock_test.go, pkg/lockfile/types.go, pkg/models/results.go, pkg/osvscanner/osvscanner.go, pkg/osvscanner/vulnerability_result.go
- Extracting name location the same way we did for version (go only)
- Wiring name location extraction up to the grouper to be taken into account in the reporter
=> ✨ Adding name location for go

cmd/osv-scanner/main_test.go, internal/utility/fileposition/string.go, pkg/lockfile/parse-go-lock.go, pkg/lockfile/parse-go-lock_test.go
We realized that the logic to find any substring in an already located block could be abstracted to ease the following work on extracting the name and version in the different package managers.
This PR adds the generic function `ExtractStringPositionInBlock` and refactor the go lockfile parser to use it.
=> ♻️ ExtractStringPositionInBlock utility 

cmd/osv-scanner/main_test.go, internal/utility/fileposition/string.go, pkg/lockfile/parse-go-lock.go, pkg/lockfile/parse-go-lock_test.go, pkg/lockfile/parse-requirements-txt.go, pkg/lockfile/parse-requirements-txt_test.go
Extract name and version location in requirements.txt parser
NOTE: In order to persist position information on the line that is passed to `parseLine` method, the "\n" char is included when there is a line continuation
=> ✨Extract name and version location in requirements.txt parser

cmd/osv-scanner/main_test.go, internal/cachedregexp/regex.go, internal/utility/fileposition/string.go, pkg/grouper/package_grouper.go, pkg/lockfile/parse-go-lock.go, pkg/lockfile/parse-maven-lock.go, pkg/lockfile/parse-maven-lock_test.go, pkg/models/file_position.go
- Extract name and version location from maven lockfiles
- The changes have been made to try to keep the already existing logic in the maven parser
- As in maven the name and version can be in a different file than the block, thus the model has been updated
- When name or version is composed by one variable, the location is where the variable value is defined
- When name or version is composed by MORE than one variable, the location is where those variables are used (the model cannot handle reporting multiple locations)
=> ✨Extracting name and version location for maven lock files

pkg/lockfile/fixtures/maven/children/with-parent-child-project-version.xml, pkg/lockfile/fixtures/maven/parent-project-version.xml, pkg/lockfile/parse-maven-lock.go, pkg/lockfile/parse-maven-lock_test.go
- Fix NPE in maven when version is defined in child and dependency in parent lockfile
=> 🐛 Fix NPE in maven when version is defined in child and dependency in parent lockfile

cmd/osv-scanner/main_test.go
There are new CVEs in the libraries that are being used for the main test file, so the test must be updated.
=> ✅ Fix main test with new CVEs

internal/utility/fileposition/column_test.go, internal/utility/fileposition/json_test.go, internal/utility/fileposition/path_test.go, internal/utility/fileposition/string.go, internal/utility/fileposition/string_test.go, internal/utility/fileposition/toml_test.go, pkg/lockfile/parse-maven-lock.go
- Add unit test to utility/fileposition
- Update a little bit the logic for `ExtractDelimitedRegexpPositionInBlock`:
- Now, `str` is just a regexp: from `(.*)` to `.*`
- To make sure there is only one capturing group, it is set in the function
=> ✅ Add unit test to utility/fileposition

pkg/lockfile/helpers_test.go, pkg/lockfile/parse-npm-lock-v1_test.go, pkg/lockfile/parse-npm-lock-v2_test.go, pkg/lockfile/parse-pnpm-lock_test.go, pkg/lockfile/parse-yarn-lock-v1_test.go, pkg/lockfile/parse-yarn-lock-v2_test.go
For those cases where the location will refer to the source file and not the lock file, we don't want to check the locations on the package details struct (unit tests). 
To achieve this, the test helpers have been updated to allow it.
=> ♻️ expectPackage(s) without locations

pkg/lockfile/extractor.go, pkg/lockfile/match-package-json.go, pkg/lockfile/matcher-helpers_test.go, pkg/lockfile/matcher.go
Base code for matching lock files with source files
- Matching is perform automatically in `extractFromFile` (i.e. for all extractors) when the extractor "has a `Matcher`"
- This means that it'll be really easy to enrich the package details extracted from a lockfile with the positions in the source file, by just implementing the interface `ExtractorWithMatcher` in the original `Extractor``
- To isolate the unit testing of the extractors from the unit testing of the matchers, there is an override of all the matchers of the extractors with matcher in the main entry point of the `lockfile_test`module (in `matcher-helpers_test`)
- By default, the matching will success (`SuccessfulMatcher{}`)
- In case we want to test matching failing for the extractor, we may use `FailingMatcher{Error: …
=> ✨ Matcher (from lockfile to sourcefile) general logic

pkg/lockfile/fixtures/maven/no-version.xml, pkg/lockfile/parse-go-lock.go, pkg/lockfile/parse-go-lock_test.go, pkg/lockfile/parse-maven-lock.go, pkg/lockfile/parse-maven-lock_test.go, pkg/lockfile/parse-requirements-txt.go, pkg/lockfile/parse-requirements-txt_test.go, pkg/lockfile/types.go, pkg/osvscanner/osvscanner.go, pkg/osvscanner/vulnerability_result.go, pkg/reporter/sbom/cyclonedx_1_4.go, pkg/reporter/sbom/cyclonedx_1_5.go, pkg/reporter/sbom/cyclonedx_test.go
Before this PR, if a version was not extracted properly, it would have defaulted to `version=0`. This have 2 major disadvantages : 
1. As all package managers have its own way to express version, the zero-version have a different form depending on the language, making it impossible to filter in a backend
2. It adds a lot of false positive to have version 0 as it will be vulnerable to everything
This PR aims to remove this version 0 and reports all packages (even the un-scannable ones) when having the flag only-packages.
=> 🐛 Stop reporting a default version when not extracted properly

pkg/lockfile/fixtures/pnpm/exotic.yaml, pkg/lockfile/parse-pnpm-lock.go
It seems that in some rare cases (not investigated yet), a dependency in a path shape doesn't mention anything else than its registry.
This is a temporary fix to give us time to investigate more PNPM lockfile generation
=> 🐛 Guarding against exotic dependency in PNPM < v9

cmd/osv-scanner/__snapshots__/main_test.snap, cmd/osv-scanner/main.go, cmd/osv-scanner/main_test.go, cmd/osv-scanner/scan/main.go
When syncing our fork with the upstream repository, the main method has been splat in multiple functions (one per subcommand), hence overwriting an important change we made and its tests. 
This PR fixes this situation and ensure osv-scanner won't return a non-zero code
=> 🐛 Reporting an empty CycloneDX when no packages are found

.github/CODEOWNERS, .github/workflows/auto-fetch-upstream.yml
This PR do 2 things related to contributions : 
- Add a github action to auto sync upstream repository in a regular manner, it will run every monday
- Add a CODEOWNER to enforce a review by asm-vm team
=> Adding an action to auto-sync upstream repo

go.mod, go.sum, internal/utility/purl/purl.go, pkg/reporter/purl/purl.go
Downgrade `packageurl-go` to `v0.1.1` as we currently have a mismatch between what versions are using between repositories which results in different results as `v0.1.3` uses a URL encoder.
=> [STAL-2295] Downgrade `packageurl-go` to `v0.1.1`

pkg/lockfile/parse-maven-lock.go
Checks for nil before overwriting the position object.
=> Check for nil

cmd/osv-scanner/__snapshots__/main_test.snap, cmd/osv-scanner/fixtures/encoding-integration-test-locks/UTF-8/go.mod, cmd/osv-scanner/fixtures/encoding-integration-test-locks/UTF-8/go.sum, pkg/lockfile/parse-go-lock.go, pkg/lockfile/parse-go-lock_test.go
This PR aims to solve an issue with go internal links : when a replace is defined on a package, for example : 
```golang
replace go.pkg.in/foo/bar v1.0.0 => ../../foo/bar/
```
Then osv-scanner reports a purl `pkg:golang/../../foo/bar/` which is an invalid one, and which does not give any useful information about the package. To improve this, this PR stops doing the replace on such cases and instead reports the original library name and drop the version as it is a local file. The reported purl will be `pkg:golang/go.pkg.in/foo/bar`
=> Update go local folder reporting to treat it as internal dependency without known version

cmd/osv-scanner/__snapshots__/main_test.snap, pkg/lockfile/parse-go-lock.go, pkg/lockfile/parse-go-lock_test.go, pkg/lockfile/types.go, pkg/models/package_metadata.go, pkg/osvscanner/__snapshots__/vulnerability_result_internal_test.snap, pkg/osvscanner/osvscanner.go, pkg/osvscanner/vulnerability_result.go
Identify all direct dependencies and mark them with a property `osv-scanner:is-direct-dependency` set to `true` in Go
=> [Go] Report is direct dependency 

cmd/osv-scanner/__snapshots__/main_test.snap, cmd/osv-scanner/main_test.go, internal/output/sbom/cyclonedx_common.go, internal/utility/purl/package_grouper.go, internal/utility/purl/package_grouper_test.go, pkg/lockfile/match-composer_test.go, pkg/lockfile/match-gemfile_test.go, pkg/models/package_metadata.go
This PR add a metadata merging mechanism to be sure that if we have 2 dependencies with one direct and one indirect, we keep the direct tag. 
It is not perfect as we should duplicate dependencies per metadata to have a full report instead but it would need to update bom-ref which have more implication than this tool.
=> Merging metadata when grouping

cmd/osv-scanner/__snapshots__/main_test.snap, cmd/osv-scanner/__snapshots__/update_test.snap, pkg/lockfile/match-pipfile.go, pkg/lockfile/match-pipfile_test.go, pkg/lockfile/match-pyproject-toml_test.go
- Include "osv-scanner:is-direct-dependency" property on Pipenv and Poetry package managers
=> Include "osv-scanner:is-direct-dependency" property on pipfile and poetry

cmd/osv-scanner/__snapshots__/main_test.snap, pkg/lockfile/fixtures/maven/two-packages-mixed-version.xml, pkg/lockfile/parse-maven-lock.go, pkg/lockfile/parse-maven-lock_test.go
When a maven dependency is using a mix between a property and a static version, we need to report where the location is used and not where the property is declared. The only moment we want to override the property is when the property is alone in the version tag.
=> 🐛 Fixing maven version and name location on mixed sources

cmd/osv-scanner/__snapshots__/main_test.snap, cmd/osv-scanner/__snapshots__/update_test.snap, pkg/lockfile/node-modules-npm-v1_test.go, pkg/lockfile/node-modules-npm-v2_test.go, pkg/lockfile/parse-maven-lock.go, pkg/lockfile/parse-maven-lock_test.go, pkg/lockfile/parse-npm-lock-v1_test.go, pkg/lockfile/parse-npm-lock-v2_test.go, pkg/lockfile/parse-npm-lock.go
Currently, we do not mark dependencies as direct for NPM or Maven packages, which is necessary so we can filter out direct dependencies when we ingest this data.
Set the IsDirect field for NPM and Maven packages. In Maven, all packages are direct so this is always true. But in NPM, that's not the case. The heuristics for setting IsDirect to true for NPM packages is solely based on whether or not the package is present in the list of `dependencies` or `devDependencies` for the root packge `""`. When we're dealing with older npm lockfiles (v1), we always set `IsDirect` to true since everything is thrown under the dependencies object here.
=> [K9VULN-1326] feat: set IsDirect for direct dependencies in NPM and Maven packages

cmd/osv-scanner/__snapshots__/main_test.snap, pkg/lockfile/__snapshots__/match-package-json_test.snap, pkg/lockfile/match-package-json.go, pkg/lockfile/match-package-json_test.go, pkg/lockfile/parse-pnpm-lock-v9_test.go, pkg/lockfile/parse-pnpm-lock.go, pkg/lockfile/parse-pnpm-lock_test.go, pkg/lockfile/parse-yarn-lock-v1_test.go, pkg/lockfile/parse-yarn-lock-v2_test.go, pkg/lockfile/parse-yarn-lock.go
Currently, we do not mark dependencies as direct for PNPM or Yarn packages, which is necessary so we can filter out direct dependencies when we ingest this data.
Set the `IsDirect` field for PNPM and Yarn packages. In PNPM, we simply check if it's in the `specifiers` object and a corresponding version exists in either the lockfile's `dependencies`, `optionalDependencies`, or `devDependencies` for lockfile versions below 6. Otherwise, we check if the version info can be found in the `dependencies`, OR the `importers` field's "dot" `dependencies`, `optionalDependencies`, or `devDependencies`.
In Yarn, it's slightly different. There is no way to differentiate whether or not a dependency is direct or not without looking it up in `package.json`, so I've set `IsDirect` to true for all of them. …
=> [K9VULN-1326] feat: set IsDirect for direct dependencies in PNPM and Yarn packages

cmd/osv-scanner/__snapshots__/main_test.snap, pkg/lockfile/parse-gemfile-lock.go, pkg/lockfile/parse-gemfile-lock_test.go, pkg/lockfile/parse-nuget-lock-v1_test.go, pkg/lockfile/parse-nuget-lock.go
Currently, we do not mark dependencies as direct for Nuget or Bundler packages, which is necessary so we can filter out direct dependencies when we ingest this data.
Set the IsDirect field for Nuget and Bundler packages. In Nuget, we simply check if the `dependencyType` is set to `Direct`. In Bundler, it's a little more involved, since the file format of `Gemfile.lock` is not a conventional file format used, and so the manual parsing of the file has to be adjusted. Here we process the `dependencies` "table", which contains all direct dependencies listed in the `Gemfile`, so some stateful logic was added for this.
=> [K9VULN-1326] feat: set `IsDirect` for direct dependencies in Nuget and Bundler packages

cmd/osv-scanner/__snapshots__/main_test.snap, pkg/lockfile/__snapshots__/match-composer_test.snap, pkg/lockfile/match-composer.go, pkg/lockfile/match-composer_test.go, pkg/lockfile/parse-composer-lock.go, pkg/lockfile/parse-composer-lock_test.go
Currently, we do not mark dependencies as direct for Composer packages, which is necessary so we can filter out direct dependencies when we ingest this data.
Set the IsDirect field for Composer packages. In Composer, we need to use the matcher to look up the `composer.json` to figure out if the dependencies are direct or not, `composer.lock` does not contain this information.
=> [K9VULN-1326] feat: set `IsDirect` to true for direct dependencies in Composer packages

pkg/lockfile/parse-maven-lock.go
This improves the log message in Maven parsing, so we can know if the parent path file is empty (remote config) or if the parent file is unreachable for whatever reason
=> [K9VULN-2381] fix(maven): add parent path to log message when it couldn't be reached

cmd/osv-scanner/__snapshots__/update_test.snap, pkg/osvscanner/__snapshots__/vulnerability_result_internal_test.snap, pkg/osvscanner/vulnerability_result.go, pkg/osvscanner/vulnerability_result_internal_test.go
- We should ignore ranged versions in the osv scanner, as they are not supported in our system
- Scanning the following requirements [file](https://gist.github.com/rjcoulter22/489c19e91f266e43904952b679f8b691) both before and after the change
- Result before: https://gist.github.com/rjcoulter22/eab70e25e0df31ec0dc49128cec22248
- Result after: https://gist.github.com/rjcoulter22/72c76f978e02d5e8c6844833b91869df
- This also updates a snapshot that was causing a CI test to fail
- This change will have to be backported to the `datadog-sbom-generator`
=> [K9VULN-3618] Filter out packages with ranged versions

.goreleaser.yml, scripts/build_snapshot.sh
When trying to cut a new [release](https://github.com/DataDog/osv-scanner/releases/tag/v0.13.0) `goreleaser` is [failing](https://github.com/DataDog/osv-scanner/actions/runs/13768617711/job/38502729355#step:6:44) due to an issue building a tree sitter library that required `cgo`, this fixes the issue by setting the `CGO_ENABLED` flag set to 1 (true)
Reproduced error linked in failing build locally running `build_snapshot.sh` and verified command succeeded after changes were introduced 
- The goreleaser config was also modified to move off of deprecated flags as outlined [here](https://goreleaser.com/deprecations/#after_3) and [here](https://goreleaser.com/deprecations/#-rm-dist)
- The comment about `CGO` not working with goreleaser was added a while back in this upstream …
=> [K9VULN-3618] Fix `goreleaser` workflow

.github/workflows/goreleaser.yml, .goreleaser.yml
This PR aims to fix the release process now that we need to use CGO to compile osv-scanner with tree-sitter. It does that by using goreleaser-cross, the recommended tool by goreleaser team when dealing with cgo.
It works by embedding multiple compiler in a single docker container and defining for each target which compiler it have to use.
See https://github.com/goreleaser/goreleaser-cross for more information about the tool
=> Run goreleaser-cross to cross compile with cgo

.github/workflows/goreleaser.yml
This PR is a follow-up of using goreleaser as I previously forgot to pass the github token to let it publish the release
=> Fixing the github token in env vars

cmd/osv-scanner/__snapshots__/main_test.snap, pkg/lockfile/__snapshots__/match-gemfile_test.snap, pkg/lockfile/fixtures/bundler/lockfile-not-synced/Gemfile, pkg/lockfile/fixtures/bundler/lockfile-not-synced/Gemfile.lock, pkg/lockfile/match-gemfile.go, pkg/lockfile/match-gemfile_test.go
In cases where the `Gemfile.lock` was out of sync with the `Gemfile` we would panic as we were under the assumption these files would be in sync - this modifies the scanner so that we discard packages that are not present in the lockfile.
- Added unit test, ran the scanner locally on [repo](https://github.com/DataDog/system-tests/tree/main) that previously failed successfully
- Updated snapshot to get CI to pass
=> [K9VULN-4192] Skip packages not in ruby lockfile

internal/json/utils.go
We saw an error like below trying to scan a customers repo ([log here](https://app.datadoghq.com/logs?query=service%3Acode-workload-runner-sca%20panic&agg_m=count&agg_m_source=base&agg_t=count&clustering_pattern_field_path=message&cols=host%2Cservice&event=AwAAAZYXHC3wZfU3IQAAABhBWllYSER5QUFBQ2pmWGxGNXZlR1hnQUQAAAAkMDE5NjE3MWMtNjQ3OC00MzEzLWJhNGQtNDAyMmUzOTYxYTI0AAB4wA&fromUser=true&graphType=waterfall&messageDisplay=inline&refresh_mode=sliding&sort=time&spanID=7513271439295205086&storage=hot&stream_sort=desc&viz=stream&from_ts=1744139169448&to_ts=1744140069448&live=true)) - to guard against this case of a package name including a special regex character we now escape the string before inputting it as a regex
> osv-scanner panicked: regexp: Compile(`"(?P<pkgName>? …
=> Defend against regex failure

pkg/lockfile/parse-yarn-lock.go
- We are seeing an issue in which a customer's yarn lockfile is being parsed and producing a package with a name of `?`, so this adds logging to help debug how that could be happening 
- This checks if a `?` is a substring as the [log](https://app.datadoghq.com/logs?query=host%3Ai-01f5a4861aaa4b123%20service%3Acode-workload-runner-sca%20container_id%3A90e92330c00b2f427d3cc5e2e9af99b50e26e21bc1b614f0f5250941e719ac5a%20filename%3A0.log&agg_m=count&agg_m_source=base&agg_t=count&clustering_pattern_field_path=message&cols=host%2Cservice%2C%40repo_id&context_event=AZYWpEWVAABDK2ZJGPVTMQAH&event=AwAAAZYWpD9yeEklggAAABhBWllXcEVXVkFBQkRLMlpKR1BWVE1RQUcAAAAkMDE5NjE2YTQtYTE3Yy00NTMyLWI0YzctOThkZTc4MmJlN2M4AApeGQ&fromUser=true&graphType=waterfall&messageDisplay=inline&refresh_mode=sliding&sort=time&sp …
=> Add debug logging for yarn

cmd/osv-scanner/__snapshots__/main_test.snap, cmd/osv-scanner/__snapshots__/update_test.snap, pkg/lockfile/__snapshots__/match-gemspec_test.snap, pkg/lockfile/fixtures/bundler/lockfile-not-synced-with-gemspec/Gemfile.lock, pkg/lockfile/fixtures/bundler/lockfile-not-synced-with-gemspec/test.gemspec, pkg/lockfile/match-gemfile.go, pkg/lockfile/match-gemspec.go, pkg/lockfile/match-gemspec_test.go
In cases where the `Gemfile.lock` was out of sync with the `.gemspec` we would panic as we were under the assumption these files would be in sync - this modifies the scanner so that we discard packages that are not present in the lockfile.
* Added unit test
* Updated snapshot to get CI to pass
We patched the scanner for similar panics in `Gemfile`'s in https://github.com/DataDog/osv-scanner/pull/170.
=> Skip `.gemspec` packages not in `Gemfile.lock`
